### ISSUE TITLE
Functional form of dihedral potential

### ISSUE THREAD

**Issue by MasatakaYm** [cabb99/open3spn2#13]
Dear developer,

**Describe the bug**
According to Eq(1) of [the 3SPN2C DNA paper (S. G. Freeman et al., 2014 JCP)](https://pubs.aip.org/aip/jcp/article/141/16/165103/1079354/Coarse-grained-modeling-of-DNA-curvature), a cosine term of the dihedral potential is **k * (1 + cos(Φ-Φ0))**. However, I find that open3spn2 implements the cosine term of the dihedral potential with **k * (1 - cos(Φ-Φ0))**:
```
energy = K_periodic*(1-cs)-K_gaussian*exp(-dt_periodic^2/2/sigma^2);
```

**Expected behavior**
If we follow expression of the original 3SPN2C paper, the following expression is correct
```
energy = K_periodic*(1+cs)-K_gaussian*exp(-dt_periodic^2/2/sigma^2);
```

Could you tell me which one is correct, k * (1 + cos(Φ-Φ0)) or k * (1 - cos(Φ-Φ0)), as a potential function of the dihedral angle of the 3SPN2C DNA.

**Comment by cabb99** [comment]
Dear Dr. Masataka,
Thank you for bringing this to our attention.

The equation presented in the original 3SPN.2C paper, k * (1 + cos(Φ-Φ0)), appears to be a misprint. The correct form used in the implementation is indeed k * (1 - cos(Φ-Φ0)) as found in the open3spn2 article supplementary information: https://journals.plos.org/ploscompbiol/article?id=10.1371/journal.pcbi.1008308#sec015

This is because the minimum energy state should occur when the dihedral angle Φ equals the equilibrium angle Φ0. The functional form k * (1 - cos(Φ-Φ0)) will achieve this, by making the energy minimum when Φ equals Φ0.

You can verify that this functional form is also present in the original 3SPN.2 implementation by looking at the source code in dihedral_list.cpp:
https://github.com/depablogroup/LAMMPS-3SPN2/blob/dc3bc158c56a3a030af7f9371a9f32f791e068c2/dihedral_list.cpp#LL210C1-L225C1

**Comment by MasatakaYm** [comment]
Thank you for your kind reply.

I understand that original paper has misprint and the formula k*(1 - cos (Φ-Φ0))  achieves the energy minimum when Φ = Φ0. Now my concern is clear!
